batch_size: 32
learning_rate: 1e-4
epochs: 50
image_size: 256
dataset_path: "data/dataset/"
generated_images_path: "outputs/generated_images/"
model_checkpoint_path: "outputs/model_checkpoints/"
noise_scale: 0.1
circle_radius: 80  # 1/3 of the image size
